"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from typing import List, Optional

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize Sentry for error tracking (if configured)
try:
    from backend.sentry_config import init_sentry
    # Note: Sentry will be initialized after environment is loaded
except ImportError:
    pass
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env(name: str, default: Optional[str] = None, *, required: bool = False) -> Optional[str]:
    value = os.getenv(name, default)
    if required and value is None:
        raise ImproperlyConfigured(f"Missing environment variable: {name}")
    return value


def get_bool_env(name: str, default: str = "False") -> bool:
    value = get_env(name, default)
    return str(value).strip().lower() in {"1", "true", "t", "yes", "y"}


def get_list_env(name: str, default: str = "") -> List[str]:
    raw = get_env(name, default) or ""
    return [item.strip() for item in raw.split(",") if item.strip()]


# Production-safe defaults
ENVIRONMENT = get_env("DJANGO_ENV", "development")
IS_PRODUCTION = ENVIRONMENT == "production"

# SECRET_KEY is required in production
if IS_PRODUCTION:
    SECRET_KEY = get_env("DJANGO_SECRET_KEY", required=True)
else:
    SECRET_KEY = get_env(
        "DJANGO_SECRET_KEY",
        default="django-insecure-*&gpg)0!mwj9sm203j=nk7l#ej%gt*im(%3)rng-vs1-21*swn",
    )

# DEBUG should be False in production
DEBUG = get_bool_env("DJANGO_DEBUG", "False" if IS_PRODUCTION else "True")

_raw_allowed = os.getenv('DJANGO_ALLOWED_HOSTS', '')
if _raw_allowed:
    ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.209']

ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS))

VERCEL_URL = get_env("VERCEL_URL")
if VERCEL_URL:
    stripped = VERCEL_URL.replace("https://", "").replace("http://", "")
    ALLOWED_HOSTS.extend([stripped, VERCEL_URL])

ALLOWED_HOSTS = sorted({host for host in ALLOWED_HOSTS if host})


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "users",
    "businesses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

AUTH_USER_MODEL = "users.User"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

database_url = get_env("DATABASE_URL")
if database_url:
    try:
        import dj_database_url
    except ImportError as exc:
        raise ImproperlyConfigured("Install dj-database-url to use DATABASE_URL.") from exc

    DATABASES["default"] = dj_database_url.parse(
        database_url,
        conn_max_age=int(get_env("DATABASE_CONN_MAX_AGE", "600")),
        ssl_require=get_bool_env("DATABASE_SSL_REQUIRED", "True"),
    )
    DATABASES["default"]["ENGINE"] = DATABASES["default"].get("ENGINE", "django.db.backends.postgresql")

DATABASES["default"]["ATOMIC_REQUESTS"] = True


# Cache Configuration (for rate limiting and performance)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# In production, use Redis for better performance
# Uncomment and configure when Redis is available:
# REDIS_URL = get_env("REDIS_URL")
# if REDIS_URL:
#     CACHES = {
#         'default': {
#             'BACKEND': 'django_redis.cache.RedisCache',
#             'LOCATION': REDIS_URL,
#             'OPTIONS': {
#                 'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             }
#         }
#     }


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "backend.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append("rest_framework.renderers.BrowsableAPIRenderer")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MIN", "15"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


default_cors_origins = {
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:19006",
    "http://127.0.0.1:19006",
    "http://localhost:8081",
}

extra_cors_origins = set(get_list_env("CORS_ALLOWED_ORIGINS"))
if VERCEL_URL:
    extra_cors_origins.add(f"https://{VERCEL_URL}")

CORS_ALLOWED_ORIGINS = sorted(default_cors_origins.union(extra_cors_origins))
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]


CSRF_TRUSTED_ORIGINS = get_list_env("CSRF_TRUSTED_ORIGINS")
if VERCEL_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{VERCEL_URL}")
CSRF_TRUSTED_ORIGINS = sorted({origin for origin in CSRF_TRUSTED_ORIGINS if origin})


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

SESSION_COOKIE_SECURE = get_bool_env("DJANGO_SESSION_COOKIE_SECURE", str(not DEBUG))
CSRF_COOKIE_SECURE = get_bool_env("DJANGO_CSRF_COOKIE_SECURE", str(not DEBUG))
SECURE_SSL_REDIRECT = get_bool_env("DJANGO_SECURE_SSL_REDIRECT", str(not DEBUG))
SECURE_HSTS_SECONDS = int(get_env("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True")
SECURE_HSTS_PRELOAD = get_bool_env("DJANGO_SECURE_HSTS_PRELOAD", "True")
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"


EMAIL_BACKEND = get_env("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = get_env("DJANGO_DEFAULT_FROM_EMAIL", "Sessly <no-reply@example.com>")

EMAIL_CONFIG = {
    "EMAIL_HOST": get_env("EMAIL_HOST"),
    "EMAIL_PORT": get_env("EMAIL_PORT"),
    "EMAIL_HOST_USER": get_env("EMAIL_HOST_USER"),
    "EMAIL_HOST_PASSWORD": get_env("EMAIL_HOST_PASSWORD"),
    "EMAIL_USE_TLS": get_bool_env("EMAIL_USE_TLS", "True"),
    "EMAIL_USE_SSL": get_bool_env("EMAIL_USE_SSL", "False"),
    "EMAIL_TIMEOUT": get_env("EMAIL_TIMEOUT"),
}

for key, value in EMAIL_CONFIG.items():
    if value in (None, ""):
        continue
    if key == "EMAIL_PORT":
        value = int(value)
    globals()[key] = value


EMAIL_VERIFICATION_CODE_TTL_MINUTES = int(get_env("EMAIL_VERIFICATION_CODE_TTL_MINUTES", "15"))
EMAIL_VERIFICATION_ENABLED = get_bool_env("EMAIL_VERIFICATION_ENABLED", "True")
FRONTEND_BASE_URL = get_env("FRONTEND_BASE_URL", "http://localhost:3000")

GOOGLE_CALENDAR_ENABLED = get_bool_env("GOOGLE_CALENDAR_ENABLED", "False")
GOOGLE_SERVICE_ACCOUNT_FILE = get_env("GOOGLE_SERVICE_ACCOUNT_FILE")
GOOGLE_SERVICE_ACCOUNT_INFO = get_env("GOOGLE_SERVICE_ACCOUNT_INFO")
GOOGLE_DEFAULT_CALENDAR_ID = get_env("GOOGLE_DEFAULT_CALENDAR_ID")


# Logging Configuration
from backend.logging_config import get_logging_config

LOGGING = get_logging_config(debug=DEBUG, environment=ENVIRONMENT)


# Sentry Error Tracking
if IS_PRODUCTION or get_env("SENTRY_DSN"):
    try:
        from backend.sentry_config import init_sentry
        init_sentry(environment=ENVIRONMENT, debug=DEBUG)
    except Exception as e:
        print(f"⚠️  Failed to initialize Sentry: {e}")
