# Generated by Django 5.2.5 on 2026-01-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_business',
            new_name='favorite_businesses',
        ),
    ]
