# Generated by Django 5.2.5 on 2025-10-20 08:24

from datetime import time

from django.db import migrations


def create_sample_business(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    BusinessOpeningHour = apps.get_model("businesses", "BusinessOpeningHour")
    BusinessService = apps.get_model("businesses", "BusinessService")

    if Business.objects.filter(slug="stylowy-fryzjer").exists():
        return

    business = Business.objects.create(
        name="Stylowy Fryzjer",
        slug="stylowy-fryzjer",
        category="hairdresser",
        description="Testowy salon fryzjerski w centrum Warszawy.",
        email="kontakt@stylowy-fryzjer.pl",
        phone_number="+48 123 456 789",
        website_url="https://stylowy-fryzjer.pl",
        timezone="Europe/Warsaw",
        address_line1="ul. Przykladowa 12",
        address_line2="Lok. 4",
        city="Warszawa",
        postal_code="00-001",
        country="Polska",
        latitude=52.2297,
        longitude=21.0122,
    )

    hours = [
        (0, False, time(9, 0), time(18, 0)),
        (1, False, time(9, 0), time(18, 0)),
        (2, False, time(9, 0), time(18, 0)),
        (3, False, time(9, 0), time(18, 0)),
        (4, False, time(9, 0), time(18, 0)),
        (5, False, time(10, 0), time(16, 0)),
        (6, True, None, None),
    ]
    opening_objects = []
    for day, is_closed, open_time, close_time in hours:
        opening_objects.append(
            BusinessOpeningHour(
                business=business,
                day_of_week=day,
                is_closed=is_closed,
                open_time=open_time,
                close_time=close_time,
            )
        )
    BusinessOpeningHour.objects.bulk_create(opening_objects)

    BusinessService.objects.create(
        business=business,
        name="Strzyzenie meskie",
        description="Szybkie i profesjonalne strzyzenie meskie.",
        duration_minutes=45,
        buffer_minutes=15,
        price_amount=80,
        price_currency="PLN",
        color="#2196f3",
    )

    BusinessService.objects.create(
        business=business,
        name="Strzyzenie damskie",
        description="Stylizacja oraz strzyzenie damskie wraz z modelowaniem.",
        duration_minutes=60,
        buffer_minutes=15,
        price_amount=160,
        price_currency="PLN",
        color="#e91e63",
    )


def remove_sample_business(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    try:
        business = Business.objects.get(slug="stylowy-fryzjer")
    except Business.DoesNotExist:
        return
    business.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sample_business, remove_sample_business, elidable=True),
    ]
