# Generated by Django 6.0 on 2025-12-10 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="businessopeninghour",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_hours",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="businesses.businessservice",
            ),
        ),
        migrations.AddField(
            model_name="businessstaff",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="businessstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_staff_positions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="businesses.businessstaff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businessopeninghour",
            unique_together={("business", "day_of_week")},
        ),
        migrations.AlterUniqueTogether(
            name="businessstaff",
            unique_together={("business", "user")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "start"], name="businesses__busines_653a0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["customer", "start"], name="businesses__custome_cf14d6_idx"
            ),
        ),
    ]
