# Generated by Django 5.2.5 on 2026-01-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='nip',
            field=models.CharField(blank=True, help_text='Numer Identyfikacji Podatkowej (NIP)', max_length=13),
        ),
    ]
